dist: xenial
sudo: required
language: c
cache:
  ccache: true
  timeout: 1000
env:
  - SAGE_VERSION="8.8"
  - SAGE_VERSION="8.9"
  - SAGE_VERSION="9.0"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gcc g++ gfortran
install: 
  - export SAGE_MIRROR="http://mirrors.mit.edu/sage/linux/64bit"
  - export SAGE_BINARY="sage-${SAGE_VERSION}-Ubuntu_16.04-x86_64.tar.bz2"
  - export SAGE="${HOME}/SageMath/sage"
  - ./.travis_sage_install.sh
  - ${SAGE} --version
  - which gcc
  - ${SAGE} -sh -c "which gcc"
  - ccache -s
  # flipper needs networkx; we force it to use a recent version if available so we do not
  # see deprecation warnings issued by the version that comes with SageMath; see https://github.com/MarkCBell/flipper/pull/4
  - ${SAGE} -pip install 'networkx>=2.4' || true
  - ${SAGE} -pip install flipper
  - ${SAGE} -pip install surface_dynamics
  - ${SAGE} -pip install --verbose --no-index --user .
script:
  - ${SAGE} -t --force-lib --long --optional=sage,flipper flatsurf
  - ${SAGE} -t --force-lib --long --optional=sage,flipper doc
