language: python
os:
  - linux
env:
  - SAGE_VERSION="8.8"
  - SAGE_VERSION="8.9"
  - SAGE_VERSION="9.0"
  - SAGE_VERSION="9.1"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda update -q conda
  - conda info -a
install:
  - conda create -q -n test-environment -c flatsurf sagelib=$SAGE_VERSION pip pyeantic pyexactreal surface-dynamics ipywidgets scipy
  - conda activate test-environment
  - pip install flipper
  - pip install --verbose --no-index .
script:
  - sage -t --force-lib --long --optional=sage,flipper,eantic,exactreal flatsurf doc
