# This environment.yml can be used to create a conda environment with
# sage-flatsurf installed. It is used for our demo binders.
name: binder
channels:
  - flatsurf
  - conda-forge
dependencies:
  - notebook
  - pyflatsurf>=3.4.0
  - sage-flatsurf
