name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  build-manual:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update -n test --quiet -f flatsurf/environment.yml
          mamba env update -n test --quiet -f flatsurf/environment.extra.yml
          mamba env update -n test --quiet -f doc/environment.yml
          conda list
      - name: build documentation
        shell: bash -l {0}
        run: |
          cd doc
          make html
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/manual/html
          TARGET_FOLDER: manual
        if: ${{ github.event_name == 'push' }}
