name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - optionals: "sage,flipper"
            packages: "sagelib=8.8"
          - optionals: "sage,flipper"
            packages: "sagelib=8.9"
          - optionals: "sage,flipper,eantic,exactreal,pyflatsurf"
            packages: "sagelib=9.1 pyflatsurf>=1.1.0 pyeantic>=1.1.1 pyexactreal>=1.3.0"
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba install --yes --quiet pip pytest pytest-xdist surface-dynamics ipywidgets scipy matplotlib-base gap-defaults ${{ matrix.packages }}
          conda activate test
          pip install flipper
      - name: Install sage-flatsurf
        shell: bash -l {0}
        run: |
          pip install --verbose --no-index .
          # Show message about cppyy regenerating pre-compiled headers so it does not show during the tests
          python -c 'import cppyy' || true
      - name: Run SageMath doctests
        shell: bash -l {0}
        run: sage -tp --force-lib --long --optional=${{ matrix.optionals }} flatsurf doc
      - name: Run pytest
        shell: bash -l {0}
        run: pytest -n auto
      - name: Show logs
        run: grep "" /dev/null `find -name '*.log'` || true
        if: ${{ always() }}

env:
  MAKEFLAGS: -j2
  SAGE_NUM_THREADS: 2
